// Initialise the global array that allows the lookup of the depth of a given object
// GM2.0 does not have a depth on objects so on import from 1.x a global array is created
// NOTE: MacroExpansion is used to insert the array initialisation at import time
gml_pragma( "global", "__global_object_depths()");

// insert the generated arrays here
global.__objectDepths[0] = -1000000; // objWorld
global.__objectDepths[1] = 0; // objCamera
global.__objectDepths[2] = 0; // objSmoothCamera
global.__objectDepths[3] = 0; // objPlayMusic
global.__objectDepths[4] = 0; // objTitleMenu
global.__objectDepths[5] = 0; // objDifficultyMenu
global.__objectDepths[6] = 0; // objOptionsMenu
global.__objectDepths[7] = 0; // objKeyboardControlsMenu
global.__objectDepths[8] = 0; // objControllerMenu
global.__objectDepths[9] = -10; // objPlayerStart
global.__objectDepths[10] = -10; // objPlayer
global.__objectDepths[11] = -11; // objBow
global.__objectDepths[12] = -1; // objBullet
global.__objectDepths[13] = 0; // objBloodEmitter
global.__objectDepths[14] = -10; // objBlood
global.__objectDepths[15] = -100; // objGameOver
global.__objectDepths[16] = 100; // objBlock
global.__objectDepths[17] = 100; // objMiniBlock
global.__objectDepths[18] = 0; // objBetterBlockDonutBlock
global.__objectDepths[19] = 0; // objBetterBlockExpandBlock
global.__objectDepths[20] = 0; // objBetterBlockExpandCtrl
global.__objectDepths[21] = 0; // objBetterBlockHammer
global.__objectDepths[22] = 0; // objBetterBlockHammerBro
global.__objectDepths[23] = 0; // objBetterBlockHammerBrosBlock
global.__objectDepths[24] = 0; // objBetterBlockScalingBlock
global.__objectDepths[25] = 1; // objBetterBlockWheelCtrl
global.__objectDepths[26] = 0; // objBetterBlockWheelPlatform
global.__objectDepths[27] = 0; // objBetterBlock
global.__objectDepths[28] = 100; // objSlipBlock
global.__objectDepths[29] = 0; // objBlockInvis
global.__objectDepths[30] = 0; // objBlockFake
global.__objectDepths[31] = 100; // objSlideBlock
global.__objectDepths[32] = 100; // objSlideBlockL
global.__objectDepths[33] = 100; // objSlideBlockR
global.__objectDepths[34] = 1; // objBossBlock
global.__objectDepths[35] = 0; // objSaveBlocker
global.__objectDepths[36] = 100; // objSlope
global.__objectDepths[37] = 100; // objSlopeDownLeft
global.__objectDepths[38] = 100; // objSlopeDownRight
global.__objectDepths[39] = 100; // objSlopeUpLeft
global.__objectDepths[40] = 100; // objSlopeUpRight
global.__objectDepths[41] = 1; // objPlatform
global.__objectDepths[42] = 1; // objBetterMovingPlatform
global.__objectDepths[43] = 1; // objMovingPlatform
global.__objectDepths[44] = 1; // objMovingPlatformNoBounce
global.__objectDepths[45] = 1; // objBlockRise
global.__objectDepths[46] = 1; // objBlockFall
global.__objectDepths[47] = 0; // objWindField
global.__objectDepths[48] = -50; // objWaterUnrefreshing
global.__objectDepths[49] = 0; // objBreakableBlock
global.__objectDepths[50] = 0; // objPushBlock
global.__objectDepths[51] = 0; // objToggleBlockEmpty
global.__objectDepths[52] = 0; // objToggleBlockFull
global.__objectDepths[53] = 0; // objBalancePlatform
global.__objectDepths[54] = 1; // objSidewaysPlatform
global.__objectDepths[55] = 0; // objJumpSpikesBehindTiles
global.__objectDepths[56] = 0; // objShurikenRotate
global.__objectDepths[57] = 0; // objJumpSpike
global.__objectDepths[58] = 0; // objJumpSpike_UpOut
global.__objectDepths[59] = 0; // objJumpSpike_UpIn
global.__objectDepths[60] = 0; // objJumpSpike_RightOut
global.__objectDepths[61] = 0; // objJumpSpike_RightIn
global.__objectDepths[62] = 0; // objJumpSpike_LeftOut
global.__objectDepths[63] = 0; // objJumpSpike_LeftIn
global.__objectDepths[64] = 0; // objJumpSpikeDownOut
global.__objectDepths[65] = 0; // objJumpSpike_DownIn
global.__objectDepths[66] = 0; // objToggleSpike
global.__objectDepths[67] = 0; // objToggleSpike_Up
global.__objectDepths[68] = 0; // objToggleSpike_UpEmpty
global.__objectDepths[69] = 0; // objToggleSpike_Right
global.__objectDepths[70] = 0; // objToggleSpike_RightEmpty
global.__objectDepths[71] = 0; // objToggleSpike_Left
global.__objectDepths[72] = 0; // objToggleSpike_LeftEmpty
global.__objectDepths[73] = 0; // objToggleSpike_Down
global.__objectDepths[74] = 0; // objToggleSpike_DownEmpty
global.__objectDepths[75] = -5; // objCherryCircle
global.__objectDepths[76] = 0; // objThwomp
global.__objectDepths[77] = 0; // objColoredWarp
global.__objectDepths[78] = 0; // objShootRefresher
global.__objectDepths[79] = 0; // objShootRefresherR
global.__objectDepths[80] = 0; // objShootRefresherL
global.__objectDepths[81] = 0; // objToggleShootRefresherR
global.__objectDepths[82] = 0; // objToggleShootRefresherL
global.__objectDepths[83] = 0; // objBoosterBlock
global.__objectDepths[84] = 0; // objBlockRefresher
global.__objectDepths[85] = 0; // objFlipBlockUp
global.__objectDepths[86] = 0; // objFlipBlockDown
global.__objectDepths[87] = 0; // objElevatorBlockUp
global.__objectDepths[88] = 0; // objElevatorBlockDown
global.__objectDepths[89] = 0; // objSingleJumpStar
global.__objectDepths[90] = 0; // objDoubleJumpStar
global.__objectDepths[91] = 0; // objTripleJumpStar
global.__objectDepths[92] = 0; // objLowGravityField
global.__objectDepths[93] = 0; // objHighGravityField
global.__objectDepths[94] = 0; // objHighSpeedField
global.__objectDepths[95] = 0; // objLowSpeedField
global.__objectDepths[96] = 0; // objLaser
global.__objectDepths[97] = 0; // objLaserOffH
global.__objectDepths[98] = 0; // objLaserOnH
global.__objectDepths[99] = 0; // objLaserOffV
global.__objectDepths[100] = 0; // objLaserOnV
global.__objectDepths[101] = 0; // objLaserSwitch
global.__objectDepths[102] = -1; // objRedBulletCannon
global.__objectDepths[103] = 100; // objRedBulletHolder
global.__objectDepths[104] = 0; // objRedBulletBill
global.__objectDepths[105] = 0; // objPurpleBeam
global.__objectDepths[106] = 0; // objYellowBeam
global.__objectDepths[107] = 0; // objBlueBeam
global.__objectDepths[108] = 0; // objRedBeam
global.__objectDepths[109] = 0; // objGreenBeam
global.__objectDepths[110] = -10; // objScreenWrapFull
global.__objectDepths[111] = 10; // objScreenWrap
global.__objectDepths[112] = 0; // objRoomStartDotkid
global.__objectDepths[113] = 0; // objDotkidSwap
global.__objectDepths[114] = -50; // objMagnetField
global.__objectDepths[115] = 0; // objRoomStartVPlayer
global.__objectDepths[116] = 0; // objVCoinA
global.__objectDepths[117] = 0; // objVCoinB
global.__objectDepths[118] = 0; // objCameraGimmick
global.__objectDepths[119] = -1; // objCameraStatue
global.__objectDepths[120] = 0; // objRedVineR
global.__objectDepths[121] = 0; // objRedVineL
global.__objectDepths[122] = 0; // objIceVineR
global.__objectDepths[123] = 0; // objIceVineL
global.__objectDepths[124] = 0; // objBlueVineR
global.__objectDepths[125] = 0; // objBlueVineL
global.__objectDepths[126] = 0; // objYellowVineR
global.__objectDepths[127] = 0; // objYellowVineL
global.__objectDepths[128] = 0; // objPurpleVineR
global.__objectDepths[129] = 0; // objPurpleVineL
global.__objectDepths[130] = 0; // objWhiteVineR
global.__objectDepths[131] = 0; // objWhiteVineL
global.__objectDepths[132] = 0; // objBlackVineR
global.__objectDepths[133] = 0; // objBlackVineL
global.__objectDepths[134] = 0; // objFireVineR
global.__objectDepths[135] = 0; // objFireVineL
global.__objectDepths[136] = 0; // objFirePart
global.__objectDepths[137] = 0; // objKidBlockUp
global.__objectDepths[138] = 0; // objKidBlockDown
global.__objectDepths[139] = 0; // objCLaserOffH
global.__objectDepths[140] = 0; // objCLaserOnH
global.__objectDepths[141] = 0; // objCLaserOffV
global.__objectDepths[142] = 0; // objCLaserOnV
global.__objectDepths[143] = 0; // objCLaserSwitch
global.__objectDepths[144] = 0; // objSpinTransitionPlayer
global.__objectDepths[145] = 0; // objRotateKidUp
global.__objectDepths[146] = 0; // objRotateKidDown
global.__objectDepths[147] = 0; // objSwitcherSpike
global.__objectDepths[148] = 0; // objGreenSpikeUp
global.__objectDepths[149] = 0; // objGreenSpikeRight
global.__objectDepths[150] = 0; // objGreenSpikeLeft
global.__objectDepths[151] = 0; // objGreenSpikeDown
global.__objectDepths[152] = 0; // objOrangeSpikeUp
global.__objectDepths[153] = 0; // objOrangeSpikeRight
global.__objectDepths[154] = 0; // objOrangeSpikeLeft
global.__objectDepths[155] = 0; // objOrangeSpikeDown
global.__objectDepths[156] = 0; // objSpikeSwitch
global.__objectDepths[157] = 0; // objPastelBlackDown
global.__objectDepths[158] = -1; // objPastelBlackUp
global.__objectDepths[159] = 0; // objPastelBlueDown
global.__objectDepths[160] = 0; // objPastelBlueLeft
global.__objectDepths[161] = 0; // objPastelBlueRight
global.__objectDepths[162] = 0; // objPastelBlueUp
global.__objectDepths[163] = 0; // objPastelGreenDown
global.__objectDepths[164] = 0; // objPastelGreenLeft
global.__objectDepths[165] = 0; // objPastelGreenRight
global.__objectDepths[166] = 0; // objPastelGreenUp
global.__objectDepths[167] = -49; // objPastelGreenWater
global.__objectDepths[168] = 0; // objPlaceholderBlock
global.__objectDepths[169] = 0; // objMuncher
global.__objectDepths[170] = 0; // objSaw
global.__objectDepths[171] = 0; // objYoshi
global.__objectDepths[172] = 0; // objYoshiControl
global.__objectDepths[173] = 0; // objYoshiDead
global.__objectDepths[174] = -10; // objYoshiLost
global.__objectDepths[175] = 0; // objChompTrap
global.__objectDepths[176] = 1; // objChompy
global.__objectDepths[177] = 0; // objSheepBlockG
global.__objectDepths[178] = 0; // objSheepBlockR
global.__objectDepths[179] = 0; // objSheepBlockY
global.__objectDepths[180] = 0; // objSheepBlockB
global.__objectDepths[181] = 0; // objSheepSpikeG
global.__objectDepths[182] = 0; // objSheepSpikeR
global.__objectDepths[183] = 0; // objSheepSpikeY
global.__objectDepths[184] = 0; // objSheepSpikeB
global.__objectDepths[185] = -1000001; // objHPbar
global.__objectDepths[186] = -1000000; // objHPbar2
global.__objectDepths[187] = -999999; // objHPbg
global.__objectDepths[188] = -999998; // objHPside
global.__objectDepths[189] = 0; // objSampleOscillator
global.__objectDepths[190] = -10; // objNotAnotherSecretItem
global.__objectDepths[191] = 0; // objPlayerKiller
global.__objectDepths[192] = 10; // objSpikeUp
global.__objectDepths[193] = 10; // objSpikeRight
global.__objectDepths[194] = 10; // objSpikeLeft
global.__objectDepths[195] = 10; // objSpikeDown
global.__objectDepths[196] = 10; // objMiniUp
global.__objectDepths[197] = 10; // objMiniRight
global.__objectDepths[198] = 10; // objMiniLeft
global.__objectDepths[199] = 10; // objMiniDown
global.__objectDepths[200] = 0; // objCherry
global.__objectDepths[201] = 0; // objCherryBounce
global.__objectDepths[202] = 0; // objCherryBounceRandom
global.__objectDepths[203] = 0; // objCherryBounceLat
global.__objectDepths[204] = 0; // objCherryBounceVert
global.__objectDepths[205] = 0; // objCherryNotDestroyOutsideRoom
global.__objectDepths[206] = 0; // objKillerBlock
global.__objectDepths[207] = 0; // objFreeTrigger
global.__objectDepths[208] = 0; // objTriggerButton
global.__objectDepths[209] = 0; // objKillerTrigger
global.__objectDepths[210] = 10; // objSpikeTriggerUp
global.__objectDepths[211] = 10; // objSpikeTriggerRight
global.__objectDepths[212] = 10; // objSpikeTriggerLeft
global.__objectDepths[213] = 10; // objSpikeTriggerDown
global.__objectDepths[214] = 0; // objCherryTrigger
global.__objectDepths[215] = -50; // objWater
global.__objectDepths[216] = -50; // objWater2
global.__objectDepths[217] = -50; // objWater3
global.__objectDepths[218] = 11; // objWalljumpR
global.__objectDepths[219] = 11; // objWalljumpL
global.__objectDepths[220] = 0; // objJumpRefresher
global.__objectDepths[221] = 10; // objSign
global.__objectDepths[222] = 0; // objGravityUp
global.__objectDepths[223] = 0; // objGravityDown
global.__objectDepths[224] = 0; // objBetterBlockCtrl
global.__objectDepths[225] = 1; // objSaveMedium
global.__objectDepths[226] = 1; // objSave
global.__objectDepths[227] = 1; // objSaveVHard
global.__objectDepths[228] = 1; // objSaveMediumFlip
global.__objectDepths[229] = 1; // objSaveFlip
global.__objectDepths[230] = 1; // objSaveVHardFlip
global.__objectDepths[231] = 0; // objWarpStart
global.__objectDepths[232] = 10; // objRoomChanger
global.__objectDepths[233] = 0; // objWarp
global.__objectDepths[234] = 0; // objWarpNext
global.__objectDepths[235] = 0; // objWarpAutosaveNext
global.__objectDepths[236] = 10; // objOutsideRoomChanger
global.__objectDepths[237] = 0; // objSecretItem
global.__objectDepths[238] = 0; // objSecretIndicator
global.__objectDepths[239] = 0; // objBossItem
global.__objectDepths[240] = 0; // objBossIndicator
global.__objectDepths[241] = 0; // objGameClear
global.__objectDepths[242] = 0; // add_your_custom_objects_here
global.__objectDepths[243] = -9999; // objAlexWorldTracker
global.__objectDepths[244] = 100; // objAlexTowerController
global.__objectDepths[245] = 110; // objAlexWaveController
global.__objectDepths[246] = 99; // objAlexControlDisplay
global.__objectDepths[247] = -1010; // objAlexGameOver
global.__objectDepths[248] = -1010; // objAlexRestartPrompt
global.__objectDepths[249] = -502; // objAlexSellArea
global.__objectDepths[250] = 0; // objAlexActor
global.__objectDepths[251] = -21; // objAlexBlock
global.__objectDepths[252] = 1; // objAlexPlatform
global.__objectDepths[253] = 0; // objAlexEnemy
global.__objectDepths[254] = 0; // objAlexHiddenEnemy
global.__objectDepths[255] = 0; // objAlexEnemyGoal
global.__objectDepths[256] = 0; // objAlexEnemyKilledVFX
global.__objectDepths[257] = 0; // objAlexEnemyDummy
global.__objectDepths[258] = 0; // objAlexEnemyHealthyJar
global.__objectDepths[259] = 0; // objAlexEnemyHungryTag
global.__objectDepths[260] = 0; // objAlexEnemyTrollface
global.__objectDepths[261] = 0; // objAlexEnemyCursedTrollface
global.__objectDepths[262] = 0; // objAlexEnemyRamboTag
global.__objectDepths[263] = 0; // objAlexEnemySoldierTag
global.__objectDepths[264] = 0; // objAlexEnemySpitter
global.__objectDepths[265] = 0; // objAlexEnemyZappyTag
global.__objectDepths[266] = 0; // objAlexEnemySleepyTag
global.__objectDepths[267] = 0; // objAlexSleepyTagExplosion
global.__objectDepths[268] = 0; // objAlexEnemyNinjaFruit
global.__objectDepths[269] = 0; // objAlexEnemyFruitWarrior
global.__objectDepths[270] = 0; // objAlexFruitWarriorHiddenForm
global.__objectDepths[271] = 0; // objAlexEnemyBlueberapple
global.__objectDepths[272] = 0; // objAlexEnemySlimmy
global.__objectDepths[273] = -500; // objAlexEnemyProjectile
global.__objectDepths[274] = 0; // objAlexStickySubstance
global.__objectDepths[275] = 0; // objAlexSoldierTagProjectile
global.__objectDepths[276] = 0; // objAlexZappyTagProjectile
global.__objectDepths[277] = 0; // objAlexSpitterProjectile
global.__objectDepths[278] = 0; // objAlexCursedTrollFaceProjectile
global.__objectDepths[279] = 10; // objAlexBlueberappleSplash
global.__objectDepths[280] = 10; // objAlexSlimmySplash
global.__objectDepths[281] = 0; // objAlexPlayer
global.__objectDepths[282] = 110; // objAlexHealthBar
global.__objectDepths[283] = 0; // objAlexTowerBlocker
global.__objectDepths[284] = 0; // objAlexTowerStunner
global.__objectDepths[285] = 0; // objAlexTower
global.__objectDepths[286] = 0; // objAlexAimerTower
global.__objectDepths[287] = 0; // objAlexOctoTower
global.__objectDepths[288] = 0; // objAlexSpiralTower
global.__objectDepths[289] = 0; // objAlexBlasterTower
global.__objectDepths[290] = 0; // objAlexSprayerTower
global.__objectDepths[291] = 0; // objAlexBouncerTower
global.__objectDepths[292] = -500; // objAlexProjectile
global.__objectDepths[293] = -501; // objAlexProjectileImpact
global.__objectDepths[294] = 0; // objAlexBlasterExplosion
global.__objectDepths[295] = 0; // objAlexBouncerExplosion
global.__objectDepths[296] = -500; // objAlexAimerProjectile
global.__objectDepths[297] = -500; // objAlexBlasterProjectile
global.__objectDepths[298] = -500; // objAlexOctoProjectile
global.__objectDepths[299] = -500; // objAlexSpiralProjectile
global.__objectDepths[300] = -500; // objAlexSprayerProjectile
global.__objectDepths[301] = -500; // objAlexBouncerProjectile
global.__objectDepths[302] = -500; // objAlexBouncerMiniProjectile
global.__objectDepths[303] = 0; // objAlexCoin
global.__objectDepths[304] = 0; // objAlexHeart
global.__objectDepths[305] = 0; // objAlexCoinGone
global.__objectDepths[306] = 0; // objAlexBronzeCoin
global.__objectDepths[307] = 0; // objAlexSilverCoin
global.__objectDepths[308] = 0; // objAlexGoldenCoin
global.__objectDepths[309] = 0; // objAlexPathArrowSpawner
global.__objectDepths[310] = 0; // objAlexPathArrow
global.__objectDepths[311] = 0; // objAlexScreenShake
global.__objectDepths[312] = -501; // objAlexVignetteEffect
global.__objectDepths[313] = 0; // objAlexParticle
global.__objectDepths[314] = -1020; // objAlexFadeInRoom
global.__objectDepths[315] = 0; // objAlexFinishBeam
global.__objectDepths[316] = 0; // objAlexFinishBeamBlast


global.__objectNames[0] = "objWorld";
global.__objectNames[1] = "objCamera";
global.__objectNames[2] = "objSmoothCamera";
global.__objectNames[3] = "objPlayMusic";
global.__objectNames[4] = "objTitleMenu";
global.__objectNames[5] = "objDifficultyMenu";
global.__objectNames[6] = "objOptionsMenu";
global.__objectNames[7] = "objKeyboardControlsMenu";
global.__objectNames[8] = "objControllerMenu";
global.__objectNames[9] = "objPlayerStart";
global.__objectNames[10] = "objPlayer";
global.__objectNames[11] = "objBow";
global.__objectNames[12] = "objBullet";
global.__objectNames[13] = "objBloodEmitter";
global.__objectNames[14] = "objBlood";
global.__objectNames[15] = "objGameOver";
global.__objectNames[16] = "objBlock";
global.__objectNames[17] = "objMiniBlock";
global.__objectNames[18] = "objBetterBlockDonutBlock";
global.__objectNames[19] = "objBetterBlockExpandBlock";
global.__objectNames[20] = "objBetterBlockExpandCtrl";
global.__objectNames[21] = "objBetterBlockHammer";
global.__objectNames[22] = "objBetterBlockHammerBro";
global.__objectNames[23] = "objBetterBlockHammerBrosBlock";
global.__objectNames[24] = "objBetterBlockScalingBlock";
global.__objectNames[25] = "objBetterBlockWheelCtrl";
global.__objectNames[26] = "objBetterBlockWheelPlatform";
global.__objectNames[27] = "objBetterBlock";
global.__objectNames[28] = "objSlipBlock";
global.__objectNames[29] = "objBlockInvis";
global.__objectNames[30] = "objBlockFake";
global.__objectNames[31] = "objSlideBlock";
global.__objectNames[32] = "objSlideBlockL";
global.__objectNames[33] = "objSlideBlockR";
global.__objectNames[34] = "objBossBlock";
global.__objectNames[35] = "objSaveBlocker";
global.__objectNames[36] = "objSlope";
global.__objectNames[37] = "objSlopeDownLeft";
global.__objectNames[38] = "objSlopeDownRight";
global.__objectNames[39] = "objSlopeUpLeft";
global.__objectNames[40] = "objSlopeUpRight";
global.__objectNames[41] = "objPlatform";
global.__objectNames[42] = "objBetterMovingPlatform";
global.__objectNames[43] = "objMovingPlatform";
global.__objectNames[44] = "objMovingPlatformNoBounce";
global.__objectNames[45] = "objBlockRise";
global.__objectNames[46] = "objBlockFall";
global.__objectNames[47] = "objWindField";
global.__objectNames[48] = "objWaterUnrefreshing";
global.__objectNames[49] = "objBreakableBlock";
global.__objectNames[50] = "objPushBlock";
global.__objectNames[51] = "objToggleBlockEmpty";
global.__objectNames[52] = "objToggleBlockFull";
global.__objectNames[53] = "objBalancePlatform";
global.__objectNames[54] = "objSidewaysPlatform";
global.__objectNames[55] = "objJumpSpikesBehindTiles";
global.__objectNames[56] = "objShurikenRotate";
global.__objectNames[57] = "objJumpSpike";
global.__objectNames[58] = "objJumpSpike_UpOut";
global.__objectNames[59] = "objJumpSpike_UpIn";
global.__objectNames[60] = "objJumpSpike_RightOut";
global.__objectNames[61] = "objJumpSpike_RightIn";
global.__objectNames[62] = "objJumpSpike_LeftOut";
global.__objectNames[63] = "objJumpSpike_LeftIn";
global.__objectNames[64] = "objJumpSpikeDownOut";
global.__objectNames[65] = "objJumpSpike_DownIn";
global.__objectNames[66] = "objToggleSpike";
global.__objectNames[67] = "objToggleSpike_Up";
global.__objectNames[68] = "objToggleSpike_UpEmpty";
global.__objectNames[69] = "objToggleSpike_Right";
global.__objectNames[70] = "objToggleSpike_RightEmpty";
global.__objectNames[71] = "objToggleSpike_Left";
global.__objectNames[72] = "objToggleSpike_LeftEmpty";
global.__objectNames[73] = "objToggleSpike_Down";
global.__objectNames[74] = "objToggleSpike_DownEmpty";
global.__objectNames[75] = "objCherryCircle";
global.__objectNames[76] = "objThwomp";
global.__objectNames[77] = "objColoredWarp";
global.__objectNames[78] = "objShootRefresher";
global.__objectNames[79] = "objShootRefresherR";
global.__objectNames[80] = "objShootRefresherL";
global.__objectNames[81] = "objToggleShootRefresherR";
global.__objectNames[82] = "objToggleShootRefresherL";
global.__objectNames[83] = "objBoosterBlock";
global.__objectNames[84] = "objBlockRefresher";
global.__objectNames[85] = "objFlipBlockUp";
global.__objectNames[86] = "objFlipBlockDown";
global.__objectNames[87] = "objElevatorBlockUp";
global.__objectNames[88] = "objElevatorBlockDown";
global.__objectNames[89] = "objSingleJumpStar";
global.__objectNames[90] = "objDoubleJumpStar";
global.__objectNames[91] = "objTripleJumpStar";
global.__objectNames[92] = "objLowGravityField";
global.__objectNames[93] = "objHighGravityField";
global.__objectNames[94] = "objHighSpeedField";
global.__objectNames[95] = "objLowSpeedField";
global.__objectNames[96] = "objLaser";
global.__objectNames[97] = "objLaserOffH";
global.__objectNames[98] = "objLaserOnH";
global.__objectNames[99] = "objLaserOffV";
global.__objectNames[100] = "objLaserOnV";
global.__objectNames[101] = "objLaserSwitch";
global.__objectNames[102] = "objRedBulletCannon";
global.__objectNames[103] = "objRedBulletHolder";
global.__objectNames[104] = "objRedBulletBill";
global.__objectNames[105] = "objPurpleBeam";
global.__objectNames[106] = "objYellowBeam";
global.__objectNames[107] = "objBlueBeam";
global.__objectNames[108] = "objRedBeam";
global.__objectNames[109] = "objGreenBeam";
global.__objectNames[110] = "objScreenWrapFull";
global.__objectNames[111] = "objScreenWrap";
global.__objectNames[112] = "objRoomStartDotkid";
global.__objectNames[113] = "objDotkidSwap";
global.__objectNames[114] = "objMagnetField";
global.__objectNames[115] = "objRoomStartVPlayer";
global.__objectNames[116] = "objVCoinA";
global.__objectNames[117] = "objVCoinB";
global.__objectNames[118] = "objCameraGimmick";
global.__objectNames[119] = "objCameraStatue";
global.__objectNames[120] = "objRedVineR";
global.__objectNames[121] = "objRedVineL";
global.__objectNames[122] = "objIceVineR";
global.__objectNames[123] = "objIceVineL";
global.__objectNames[124] = "objBlueVineR";
global.__objectNames[125] = "objBlueVineL";
global.__objectNames[126] = "objYellowVineR";
global.__objectNames[127] = "objYellowVineL";
global.__objectNames[128] = "objPurpleVineR";
global.__objectNames[129] = "objPurpleVineL";
global.__objectNames[130] = "objWhiteVineR";
global.__objectNames[131] = "objWhiteVineL";
global.__objectNames[132] = "objBlackVineR";
global.__objectNames[133] = "objBlackVineL";
global.__objectNames[134] = "objFireVineR";
global.__objectNames[135] = "objFireVineL";
global.__objectNames[136] = "objFirePart";
global.__objectNames[137] = "objKidBlockUp";
global.__objectNames[138] = "objKidBlockDown";
global.__objectNames[139] = "objCLaserOffH";
global.__objectNames[140] = "objCLaserOnH";
global.__objectNames[141] = "objCLaserOffV";
global.__objectNames[142] = "objCLaserOnV";
global.__objectNames[143] = "objCLaserSwitch";
global.__objectNames[144] = "objSpinTransitionPlayer";
global.__objectNames[145] = "objRotateKidUp";
global.__objectNames[146] = "objRotateKidDown";
global.__objectNames[147] = "objSwitcherSpike";
global.__objectNames[148] = "objGreenSpikeUp";
global.__objectNames[149] = "objGreenSpikeRight";
global.__objectNames[150] = "objGreenSpikeLeft";
global.__objectNames[151] = "objGreenSpikeDown";
global.__objectNames[152] = "objOrangeSpikeUp";
global.__objectNames[153] = "objOrangeSpikeRight";
global.__objectNames[154] = "objOrangeSpikeLeft";
global.__objectNames[155] = "objOrangeSpikeDown";
global.__objectNames[156] = "objSpikeSwitch";
global.__objectNames[157] = "objPastelBlackDown";
global.__objectNames[158] = "objPastelBlackUp";
global.__objectNames[159] = "objPastelBlueDown";
global.__objectNames[160] = "objPastelBlueLeft";
global.__objectNames[161] = "objPastelBlueRight";
global.__objectNames[162] = "objPastelBlueUp";
global.__objectNames[163] = "objPastelGreenDown";
global.__objectNames[164] = "objPastelGreenLeft";
global.__objectNames[165] = "objPastelGreenRight";
global.__objectNames[166] = "objPastelGreenUp";
global.__objectNames[167] = "objPastelGreenWater";
global.__objectNames[168] = "objPlaceholderBlock";
global.__objectNames[169] = "objMuncher";
global.__objectNames[170] = "objSaw";
global.__objectNames[171] = "objYoshi";
global.__objectNames[172] = "objYoshiControl";
global.__objectNames[173] = "objYoshiDead";
global.__objectNames[174] = "objYoshiLost";
global.__objectNames[175] = "objChompTrap";
global.__objectNames[176] = "objChompy";
global.__objectNames[177] = "objSheepBlockG";
global.__objectNames[178] = "objSheepBlockR";
global.__objectNames[179] = "objSheepBlockY";
global.__objectNames[180] = "objSheepBlockB";
global.__objectNames[181] = "objSheepSpikeG";
global.__objectNames[182] = "objSheepSpikeR";
global.__objectNames[183] = "objSheepSpikeY";
global.__objectNames[184] = "objSheepSpikeB";
global.__objectNames[185] = "objHPbar";
global.__objectNames[186] = "objHPbar2";
global.__objectNames[187] = "objHPbg";
global.__objectNames[188] = "objHPside";
global.__objectNames[189] = "objSampleOscillator";
global.__objectNames[190] = "objNotAnotherSecretItem";
global.__objectNames[191] = "objPlayerKiller";
global.__objectNames[192] = "objSpikeUp";
global.__objectNames[193] = "objSpikeRight";
global.__objectNames[194] = "objSpikeLeft";
global.__objectNames[195] = "objSpikeDown";
global.__objectNames[196] = "objMiniUp";
global.__objectNames[197] = "objMiniRight";
global.__objectNames[198] = "objMiniLeft";
global.__objectNames[199] = "objMiniDown";
global.__objectNames[200] = "objCherry";
global.__objectNames[201] = "objCherryBounce";
global.__objectNames[202] = "objCherryBounceRandom";
global.__objectNames[203] = "objCherryBounceLat";
global.__objectNames[204] = "objCherryBounceVert";
global.__objectNames[205] = "objCherryNotDestroyOutsideRoom";
global.__objectNames[206] = "objKillerBlock";
global.__objectNames[207] = "objFreeTrigger";
global.__objectNames[208] = "objTriggerButton";
global.__objectNames[209] = "objKillerTrigger";
global.__objectNames[210] = "objSpikeTriggerUp";
global.__objectNames[211] = "objSpikeTriggerRight";
global.__objectNames[212] = "objSpikeTriggerLeft";
global.__objectNames[213] = "objSpikeTriggerDown";
global.__objectNames[214] = "objCherryTrigger";
global.__objectNames[215] = "objWater";
global.__objectNames[216] = "objWater2";
global.__objectNames[217] = "objWater3";
global.__objectNames[218] = "objWalljumpR";
global.__objectNames[219] = "objWalljumpL";
global.__objectNames[220] = "objJumpRefresher";
global.__objectNames[221] = "objSign";
global.__objectNames[222] = "objGravityUp";
global.__objectNames[223] = "objGravityDown";
global.__objectNames[224] = "objBetterBlockCtrl";
global.__objectNames[225] = "objSaveMedium";
global.__objectNames[226] = "objSave";
global.__objectNames[227] = "objSaveVHard";
global.__objectNames[228] = "objSaveMediumFlip";
global.__objectNames[229] = "objSaveFlip";
global.__objectNames[230] = "objSaveVHardFlip";
global.__objectNames[231] = "objWarpStart";
global.__objectNames[232] = "objRoomChanger";
global.__objectNames[233] = "objWarp";
global.__objectNames[234] = "objWarpNext";
global.__objectNames[235] = "objWarpAutosaveNext";
global.__objectNames[236] = "objOutsideRoomChanger";
global.__objectNames[237] = "objSecretItem";
global.__objectNames[238] = "objSecretIndicator";
global.__objectNames[239] = "objBossItem";
global.__objectNames[240] = "objBossIndicator";
global.__objectNames[241] = "objGameClear";
global.__objectNames[242] = "add_your_custom_objects_here";
global.__objectNames[243] = "objAlexWorldTracker";
global.__objectNames[244] = "objAlexTowerController";
global.__objectNames[245] = "objAlexWaveController";
global.__objectNames[246] = "objAlexControlDisplay";
global.__objectNames[247] = "objAlexGameOver";
global.__objectNames[248] = "objAlexRestartPrompt";
global.__objectNames[249] = "objAlexSellArea";
global.__objectNames[250] = "objAlexActor";
global.__objectNames[251] = "objAlexBlock";
global.__objectNames[252] = "objAlexPlatform";
global.__objectNames[253] = "objAlexEnemy";
global.__objectNames[254] = "objAlexHiddenEnemy";
global.__objectNames[255] = "objAlexEnemyGoal";
global.__objectNames[256] = "objAlexEnemyKilledVFX";
global.__objectNames[257] = "objAlexEnemyDummy";
global.__objectNames[258] = "objAlexEnemyHealthyJar";
global.__objectNames[259] = "objAlexEnemyHungryTag";
global.__objectNames[260] = "objAlexEnemyTrollface";
global.__objectNames[261] = "objAlexEnemyCursedTrollface";
global.__objectNames[262] = "objAlexEnemyRamboTag";
global.__objectNames[263] = "objAlexEnemySoldierTag";
global.__objectNames[264] = "objAlexEnemySpitter";
global.__objectNames[265] = "objAlexEnemyZappyTag";
global.__objectNames[266] = "objAlexEnemySleepyTag";
global.__objectNames[267] = "objAlexSleepyTagExplosion";
global.__objectNames[268] = "objAlexEnemyNinjaFruit";
global.__objectNames[269] = "objAlexEnemyFruitWarrior";
global.__objectNames[270] = "objAlexFruitWarriorHiddenForm";
global.__objectNames[271] = "objAlexEnemyBlueberapple";
global.__objectNames[272] = "objAlexEnemySlimmy";
global.__objectNames[273] = "objAlexEnemyProjectile";
global.__objectNames[274] = "objAlexStickySubstance";
global.__objectNames[275] = "objAlexSoldierTagProjectile";
global.__objectNames[276] = "objAlexZappyTagProjectile";
global.__objectNames[277] = "objAlexSpitterProjectile";
global.__objectNames[278] = "objAlexCursedTrollFaceProjectile";
global.__objectNames[279] = "objAlexBlueberappleSplash";
global.__objectNames[280] = "objAlexSlimmySplash";
global.__objectNames[281] = "objAlexPlayer";
global.__objectNames[282] = "objAlexHealthBar";
global.__objectNames[283] = "objAlexTowerBlocker";
global.__objectNames[284] = "objAlexTowerStunner";
global.__objectNames[285] = "objAlexTower";
global.__objectNames[286] = "objAlexAimerTower";
global.__objectNames[287] = "objAlexOctoTower";
global.__objectNames[288] = "objAlexSpiralTower";
global.__objectNames[289] = "objAlexBlasterTower";
global.__objectNames[290] = "objAlexSprayerTower";
global.__objectNames[291] = "objAlexBouncerTower";
global.__objectNames[292] = "objAlexProjectile";
global.__objectNames[293] = "objAlexProjectileImpact";
global.__objectNames[294] = "objAlexBlasterExplosion";
global.__objectNames[295] = "objAlexBouncerExplosion";
global.__objectNames[296] = "objAlexAimerProjectile";
global.__objectNames[297] = "objAlexBlasterProjectile";
global.__objectNames[298] = "objAlexOctoProjectile";
global.__objectNames[299] = "objAlexSpiralProjectile";
global.__objectNames[300] = "objAlexSprayerProjectile";
global.__objectNames[301] = "objAlexBouncerProjectile";
global.__objectNames[302] = "objAlexBouncerMiniProjectile";
global.__objectNames[303] = "objAlexCoin";
global.__objectNames[304] = "objAlexHeart";
global.__objectNames[305] = "objAlexCoinGone";
global.__objectNames[306] = "objAlexBronzeCoin";
global.__objectNames[307] = "objAlexSilverCoin";
global.__objectNames[308] = "objAlexGoldenCoin";
global.__objectNames[309] = "objAlexPathArrowSpawner";
global.__objectNames[310] = "objAlexPathArrow";
global.__objectNames[311] = "objAlexScreenShake";
global.__objectNames[312] = "objAlexVignetteEffect";
global.__objectNames[313] = "objAlexParticle";
global.__objectNames[314] = "objAlexFadeInRoom";
global.__objectNames[315] = "objAlexFinishBeam";
global.__objectNames[316] = "objAlexFinishBeamBlast";


// create another array that has the correct entries
var len = array_length_1d(global.__objectDepths);
global.__objectID2Depth = [];
for( var i=0; i<len; ++i ) {
	var objID = asset_get_index( global.__objectNames[i] );
	if (objID >= 0) {
		global.__objectID2Depth[ objID ] = global.__objectDepths[i];
	} // end if
} // end for